In [5]:
import numpy as np
def random_orthogonal_matrix(n):
    random_matrix = np.random.rand(n,n)
    Q , R = np.linalg.qr(random_matrix)  # Phân rã QR để lấy Q (ma trận trực giao) và R là ma trận tam giác trên
    return Q,R
Q,R = random_orthogonal_matrix(3)
print("Ma trận trực giao 3x3:\n", Q)
print("ma trận tam giác trên:\n",R)

Ma trận trực giao 3x3:
 [[-0.06327049  0.4305391  -0.90035156]
 [-0.95118584 -0.29907125 -0.0761701 ]
 [-0.30206347  0.85158234  0.42844508]]
ma trận tam giác trên:
 [[-0.56094185 -1.17882988 -0.2914456 ]
 [ 0.          0.74509444  0.76242325]
 [ 0.          0.         -0.3346751 ]]
