In [2]:
import numpy as np

In [38]:
m = int(input('số hàng của ma trận là:'))
n = int(input('số cột của ma trận là:'))

số hàng của ma trận là: 2
số cột của ma trận là: 2


In [40]:
A = np.zeros((m,n))
for i in range(m):
    for j in range(n):
        A[i][j] = input(f'nhập phần tử hàng {i+1} cột {j+1} của ma trận A:')      
        print(A, '\n')
print('ta có ma trận A:')
print(A)

nhập phần tử hàng 1 cột 1 của ma trận A: 1


[[1. 0.]
 [0. 0.]] 



nhập phần tử hàng 1 cột 2 của ma trận A: 2


[[1. 2.]
 [0. 0.]] 



nhập phần tử hàng 2 cột 1 của ma trận A: 3


[[1. 2.]
 [3. 0.]] 



nhập phần tử hàng 2 cột 2 của ma trận A: 4


[[1. 2.]
 [3. 4.]] 

ta có ma trận A:
[[1. 2.]
 [3. 4.]]


In [46]:
A_T = A.T
print('ta có ma trận chuyển vị là:')
print(A_T)

ta có ma trận chuyển vị là:
[[1. 3.]
 [2. 4.]]


In [48]:
import numpy as np

In [50]:
n = int(input('Hãy nhập kích thước của ma trận vuông: '))

Hãy nhập kích thước của ma trận vuông:  2


In [62]:
A = []
for i in range(n):
    row = list(map(float,input(f'Hàng {i+1}:').split()))
    A.append(row)
print(np.array(A))

Hàng 1: 1 2 
Hàng 2: 3 4


[[1. 2.]
 [3. 4.]]


In [64]:
import numpy as np

In [66]:
n = int(input('số cột của ma trận là:'))
m = int(input('số hàng của ma trận là:'))

số cột của ma trận là: 2
số hàng của ma trận là: 3


In [72]:
A = []
for i in range(n):
    row = list(map(complex, input(f"Hàng {i+1}: ").split()))
    A.append(row)
A = np.array(A, dtype=np.complex128)
print('Ma trận chuyển vị liên hợp:')
print(A.conj().T)

Hàng 1:  2 3 4
Hàng 2:  1 2 3


Ma trận chuyển vị liên hợp:
[[2.-0.j 1.-0.j]
 [3.-0.j 2.-0.j]
 [4.-0.j 3.-0.j]]
