In [2]:
import numpy as np

In [38]:
m = int(input('số hàng của ma trận là:'))
n = int(input('số cột của ma trận là:'))

số hàng của ma trận là: 2
số cột của ma trận là: 2


In [40]:
A = np.zeros((m,n))
for i in range(m):
    for j in range(n):
        A[i][j] = input(f'nhập phần tử hàng {i+1} cột {j+1} của ma trận A:')      
        print(A, '\n')
print('ta có ma trận A:')
print(A)

nhập phần tử hàng 1 cột 1 của ma trận A: 1


[[1. 0.]
 [0. 0.]] 



nhập phần tử hàng 1 cột 2 của ma trận A: 2


[[1. 2.]
 [0. 0.]] 



nhập phần tử hàng 2 cột 1 của ma trận A: 3


[[1. 2.]
 [3. 0.]] 



nhập phần tử hàng 2 cột 2 của ma trận A: 4


[[1. 2.]
 [3. 4.]] 

ta có ma trận A:
[[1. 2.]
 [3. 4.]]


In [46]:
A_T = A.T
print('ta có ma trận chuyển vị là:')
print(A_T)

ta có ma trận chuyển vị là:
[[1. 3.]
 [2. 4.]]


In [48]:
import numpy as np

In [50]:
n = int(input('Hãy nhập kích thước của ma trận vuông: '))

Hãy nhập kích thước của ma trận vuông:  2


In [62]:
A = []
for i in range(n):
    row = list(map(float,input(f'Hàng {i+1}:').split()))
    A.append(row)
print(np.array(A))

Hàng 1: 1 2 
Hàng 2: 3 4


[[1. 2.]
 [3. 4.]]


In [64]:
import numpy as np

In [66]:
n = int(input('số cột của ma trận là:'))
m = int(input('số hàng của ma trận là:'))

số cột của ma trận là: 2
số hàng của ma trận là: 3


In [72]:
A = []
for i in range(n):
    row = list(map(complex, input(f"Hàng {i+1}: ").split()))
    A.append(row)
A = np.array(A, dtype=np.complex128)
print('Ma trận chuyển vị liên hợp:')
print(A.conj().T)

Hàng 1:  2 3 4
Hàng 2:  1 2 3


Ma trận chuyển vị liên hợp:
[[2.-0.j 1.-0.j]
 [3.-0.j 2.-0.j]
 [4.-0.j 3.-0.j]]


In [1]:
import numpy as np

In [3]:
# Nhập kích thước của ma trận vuông {nxn}:
n = int(input("Nhập kích thước của ma trận vuông {n}:"))

A = []
for i in range(n):
    row = list(map(float,input(f"hàng {i+1}:").split()))
    A.append(row)
A = np.array(A)
print("\n Ma trận vuông A:")
print(A)

Nhập kích thước của ma trận vuông {n}: 3
hàng 1: 1 2 3
hàng 2: 2 3 4
hàng 3: 3 4 5



 Ma trận vuông A:
[[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]]


In [9]:
import numpy as np
def row_echelon_form(A):
    A = A.astype(float)
    rows,cols = A.shape
    pivot_row = 0
    for col in range(cols):
        max_row = pivot_row + np.argmax(np.abs(A[pivot_row:,col]))
        if A[max_row,col] == 0:
            continue
        A[[pivot_row,max_row]] = A[[max_row,pivot_row]]
        A[pivot_row] = A[pivot_row] / A[pivot_row,col]
        for row in range(pivot_row + 1,rows):
            A[row] -= A[row,col] *A[pivot_row]
        pivot_row += 1
        if pivot_row == rows:
            break
    return A
m = int(input("Nhập vào hàng:"))
n = int(input("nhập vào cột:"))
A = []
for i in range(m):
    row = list(map(float,input(f"nhập vào hàng {i+1}:").split()))
    A.append(row)
A =np.array(A)
A_ref = row_echelon_form(A.copy())
print(A_ref)

Nhập vào hàng: 2 
nhập vào cột: 2
nhập vào hàng 1: 1 2
nhập vào hàng 2: 2 3


[[1.  1.5]
 [0.  1. ]]


In [11]:
import numpy as np

In [17]:
n = int(input("nhập kích thước ma trận vuông(n): "))
A = np.random.randint(1,10,(n,n))
upper = np.triu(A)
lower = np.tril(A)
print("ma trận ban đầu:")
print(A)
print("\n ma trận tam giác trên là:")
print(upper)
print("\n ma trận tam giác dưới là:")
print(lower)

nhập kích thước ma trận vuông(n):  2


ma trận ban đầu:
[[2 5]
 [1 5]]

 ma trận tam giác trên là:
[[2 5]
 [0 5]]

 ma trận tam giác dưới là:
[[2 0]
 [1 5]]


In [29]:
import numpy as np
def tao_matran_duong(n):
    B = np.random.randint(-10,-1,(n,n))
    A = np.dot(B.T,B)
    return A,B
n = int(input("nhập vào kích thước của ma trận vuông {n}:"))
A,B = tao_matran_duong(n)
print("ta có ma trận ban đầu là:")
print(B)
print("ta có ma trận xác định dương là:")
print(A)

nhập vào kích thước của ma trận vuông {n}: 2


ta có ma trận ban đầu là:
[[-3 -8]
 [-6 -6]]
ta có ma trận xác định dương là:
[[ 45  60]
 [ 60 100]]


In [67]:
import numpy as np
m = int(input("nhập số hàng của ma trận A:"))
n = int(input("nhập vào cột của ma trận A cũng là số hàng của ma trận B:"))
p = int(input("nhập vào số cột của ma trận B:"))

print("\n Nhập vào ma trận A:")
A = np.array([[int(input(f"phần tử A[{j+1}][{i +1}]")) for i  in range(n) ] for j in range(m)])
print(A.shape)
print("\n nhập vào ma trận B:")
B = np.array([[int(input(f"phần tử B[{j+1}][{i +1}]"))for i in range(p)] for j in range(n)])
print(B.shape)

C = A@B # hoặc sử dụng dot(A,B)
D = A + B.T
print("\n nhân 2 ma trận là:")
print(C)
print("\n công 2 ma trận là:")
print(D)

nhập số hàng của ma trận A: 2
nhập vào cột của ma trận A cũng là số hàng của ma trận B: 3
nhập vào số cột của ma trận B: 2



 Nhập vào ma trận A:


phần tử A[1][1] 1
phần tử A[1][2] 1
phần tử A[1][3] 1
phần tử A[2][1] 1
phần tử A[2][2] 1
phần tử A[2][3] 1


(2, 3)

 nhập vào ma trận B:


phần tử B[1][1] 1
phần tử B[1][2] 1
phần tử B[2][1] 1
phần tử B[2][2] 1
phần tử B[3][1] 1
phần tử B[3][2] 1


(3, 2)

 nhân 2 ma trận là:
[[3 3]
 [3 3]]

 công 2 ma trận là:
[[2 2 2]
 [2 2 2]]


In [71]:
import numpy as np
n = int(input("nhập kích thước của ma trận vuông {n}:"))

print("\n nhập ma trận A:")
A = np.array([[float(input(f"A[{i}][{j}]: ")) for j in range(n)] for i in range(n)])
det_A = np.linalg.det(A)
if det_A == 0:
    print("ma trận A không phải là ma trận khả nghịch:")
else:
    A_inv = np.linalg.inv(A)
    print("\n ma trận khả nghịch của A là!")
    print(A_inv)

    print("\n kiểm tra tính khả nghịch của ma trận A:")
    print(np.round(np.dot(A,A_inv),5))

nhập kích thước của ma trận vuông {n}: 2



 nhập ma trận A:


A[0][0]:  2
A[0][1]:  3
A[1][0]:  1
A[1][1]:  4



 ma trận khả nghịch của A là!
[[ 0.8 -0.6]
 [-0.2  0.4]]

 kiểm tra tính khả nghịch của ma trận A:
[[1. 0.]
 [0. 1.]]
