In [24]:
# chapter 1
import numpy as np
from hung import input_matrix,gauss_jordan_inverse,gram_schmidt
# vd1:

In [19]:
try:
    A = input_matrix()
    A_inv = gauss_jordan_inverse(A)
    print("Ma trận nghịch đảo của A là:\n", A_inv)
except ValueError as e:
    print(e)

Nhập kích thước ma trận vuông n x n:  4


Nhập từng dòng của ma trận, cách nhau bởi dấu cách:


Dòng 1:  -1 0 1 -1
Dòng 2:  2 1 -3 4
Dòng 3:  1 2 -2 8
Dòng 4:  -2 0 2 1


Ma trận nghịch đảo của A là:
 [[-1.33333333 -2.          1.         -1.33333333]
 [ 2.33333333 -1.          1.         -1.66666667]
 [-1.         -2.          1.         -1.        ]
 [-0.66666667  0.          0.          0.33333333]]


In [15]:
try:
    B = input_matrix()
    B_inv = gauss_jordan_inverse(B)
    print("Ma trận nghịch đảo của A là:\n", B_inv)
except ValueError as e:
    print(e)

Nhập kích thước ma trận vuông n x n:  4


Nhập từng dòng của ma trận, cách nhau bởi dấu cách:


Dòng 1:  1 1 1 1
Dòng 2:  2 2 3 5
Dòng 3:  3 3 4 5
Dòng 4:  1 1 1 2


Ma trận không khả nghịch!


In [21]:
# vd2:
A_T = A.T
A_T_inv = gauss_jordan_inverse(A_T)

In [25]:
print("X:\n",np.dot(B,A_T_inv) + A)

X:
 [[ -4.66666667   0.66666667  -2.          -1.33333333]
 [ -8.33333333  -1.66666667 -11.           4.33333333]
 [-11.66666667   1.66666667 -12.           7.66666667]
 [ -7.          -1.          -2.           1.        ]]


In [36]:
import numpy as np
# vd 3:
A = input_matrix()
k = 2
print(A ** k)

Nhập kích thước ma trận vuông n x n:  2


Nhập từng dòng của ma trận, cách nhau bởi dấu cách:


Dòng 1:  1 0
Dòng 2:  0 9


[[ 1.  0.]
 [ 0. 81.]]


In [46]:
import numpy as np
#vd 4:
from sympy import symbols , Matrix, det, solve
m = symbols('m')
A = Matrix([
    [m +1 , 1 , 3],
    [2,m+2,0],
    [2*m,1,3]])
det_A = det(A)
hung = solve(det_A , m)
for i in hung:
    print(f'm != {i}')

m != -2
m != 1


In [33]:
# chapter 2
# slide 22:
import numpy as np
# Nhập vector từ người dùng
num_vectors = int(input("Nhập số chiều của vector: "))
vector_dim = int(input("Nhập số lượng vector: "))

vectors = []
print("Nhập từng vector (các phần tử cách nhau bằng dấu cách):")
for i in range(num_vectors):
    vector = list(map(float, input(f"Vector {i+1}: ").split()))
    if len(vector) != vector_dim:
        print("Lỗi: Số phần tử không đúng, vui lòng nhập lại!")
        exit()
    vectors.append(vector)
# chuyển đổi sang numpy array và thực hiện Gram-Schimidt
V = np.array(vectors).T  # Chuyển ma trận để mỗi cột là một vector

# Áp dụng Gram-Schmidt
U = gram_schmidt(V)

print("\nCác vector trực chuẩn hóa:")
print(U.T)  # Chuyển lại dạng vector ban đầu


Nhập số chiều của vector:  3
Nhập số lượng vector:  3


Nhập từng vector (các phần tử cách nhau bằng dấu cách):


Vector 1:  1 -1 1
Vector 2:  -1 1 1
Vector 3:  1 1 -1



Các vector trực chuẩn hóa:
[[ 0.57735027 -0.57735027  0.57735027]
 [-0.40824829  0.40824829  0.81649658]
 [ 0.70710678  0.70710678  0.        ]]


In [ ]:
# slide 20

In [22]:
import numpy as np  

B = [
    [1, 1, 1, 1],
    [0, 1, 1, 1],
    [1, 0, 1, 1],
    [1, 1, 0, 1]
]

S = [
    [1, 1, 0, 0],
    [0, 1, 1, 0],
    [0, 0, 1, 1],
    [1, 0, 0, 0]
]
B_matrix = np.array(B).T
print(B_matrix)
S_matrix = np.array(S).T
print(S_matrix)
det_B = np.linalg.det(B_matrix)
det_S = np.linalg.det(S_matrix)
print(f"B: {det_B}")
print(f"S: {det_S}")


P_S_from_B = np.linalg.inv(S_matrix) @ B_matrix
print("Ta có ma trận chuyển cơ sở:")
print(P_S_from_B)
print("Tọa độ vecto theo cơ sở B:")
print(np.linalg.inv(P_S_from_B) @ u_S)

[[1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]
 [1 1 1 1]]
[[1 0 0 1]
 [1 1 0 0]
 [0 1 1 0]
 [0 0 1 0]]
B: 1.0
S: -1.0
Ta có ma trận chuyển cơ sở:
[[ 1.  1.  0.  2.]
 [ 0.  0.  0. -1.]
 [ 1.  1.  1.  1.]
 [ 0. -1.  1. -1.]]
Tọa độ vecto theo cơ sở B:
[-9.  6.  4.  2.]


In [12]:
# slide 25
import numpy as np  
from hung import is_linear_mapping,find_image,find_kernel,rank_of_vectors
A = np.array([
    [1,0],
    [0,1],
    [1,1]])
print('f là ánh xa 5 tuyến tính:',is_linear_mapping(A))
print('Anh cua f la: imf = span{(1,0),(0,1),(1,1)}')
print('kerf là: kerf = {(0,0)}')
rank = np.linalg.matrix_rank(A)
nullity = A.shape[1] - rank  # Số khuyết = số biến - hạng
print(f"\nhạng của f (rank): {rank}")
print(f" Số khuyết của f (nullity): {nullity}")


f là ánh xa 5 tuyến tính: True
Anh cua f la: imf = span{(1,0),(0,1),(1,1)}
kerf là: kerf = {(0,0)}

hạng của f (rank): 2
 Số khuyết của f (nullity): 0


In [14]:
# slide 26
import numpy as np

# Giả sử ma trận A có kích thước m x n
m = int(input('số hàng của ma trận là:'))
n = int(input('số cột của ma trận là:'))
A = np.zeros((m,n))
for i in range(m):
    for j in range(n):
        A[i][j] = input(f'nhập phần tử hàng {i+1} cột {j+1} của ma trận A:')      
        print(A, '\n')
print('ta có ma trận A:')
print(A)
# Tìm hạng của ma trận A
rank = np.linalg.matrix_rank(A)

# Số chiều của Ker(f)
dim_ker = A.shape[1] - rank  # n - rank(A)

# Tìm nghiệm của hệ Ax = 0 (sử dụng SVD)
U, s, Vh = np.linalg.svd(A)
null_space_basis = Vh[rank:].T

print("Ker(f) có số chiều:", dim_ker)
print("Cơ sở của Ker(f):\n", null_space_basis)

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 2. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 2. 3.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 2. 3.]
 [1. 0. 0.]
 [0. 0. 0.]] 

[[1. 2. 3.]
 [1. 3. 0.]
 [0. 0. 0.]] 

[[1. 2. 3.]
 [1. 3. 7.]
 [0. 0. 0.]] 

[[1. 2. 3.]
 [1. 3. 7.]
 [1. 0. 0.]] 

[[1. 2. 3.]
 [1. 3. 7.]
 [1. 4. 0.]] 

[[1. 2. 3.]
 [1. 3. 7.]
 [1. 4. 5.]] 

ta có ma trận A:
[[1. 2. 3.]
 [1. 3. 7.]
 [1. 4. 5.]]
Ker(f) có số chiều: 0
Cơ sở của Ker(f):
 []
