In [24]:
# chapter 1
import numpy as np
from hung import input_matrix,gauss_jordan_inverse,gram_schmidt
# vd1:

In [19]:
try:
    A = input_matrix()
    A_inv = gauss_jordan_inverse(A)
    print("Ma trận nghịch đảo của A là:\n", A_inv)
except ValueError as e:
    print(e)

Nhập kích thước ma trận vuông n x n:  4


Nhập từng dòng của ma trận, cách nhau bởi dấu cách:


Dòng 1:  -1 0 1 -1
Dòng 2:  2 1 -3 4
Dòng 3:  1 2 -2 8
Dòng 4:  -2 0 2 1


Ma trận nghịch đảo của A là:
 [[-1.33333333 -2.          1.         -1.33333333]
 [ 2.33333333 -1.          1.         -1.66666667]
 [-1.         -2.          1.         -1.        ]
 [-0.66666667  0.          0.          0.33333333]]


In [15]:
try:
    B = input_matrix()
    B_inv = gauss_jordan_inverse(B)
    print("Ma trận nghịch đảo của A là:\n", B_inv)
except ValueError as e:
    print(e)

Nhập kích thước ma trận vuông n x n:  4


Nhập từng dòng của ma trận, cách nhau bởi dấu cách:


Dòng 1:  1 1 1 1
Dòng 2:  2 2 3 5
Dòng 3:  3 3 4 5
Dòng 4:  1 1 1 2


Ma trận không khả nghịch!


In [21]:
# vd2:
A_T = A.T
A_T_inv = gauss_jordan_inverse(A_T)

In [25]:
print("X:\n",np.dot(B,A_T_inv) + A)

X:
 [[ -4.66666667   0.66666667  -2.          -1.33333333]
 [ -8.33333333  -1.66666667 -11.           4.33333333]
 [-11.66666667   1.66666667 -12.           7.66666667]
 [ -7.          -1.          -2.           1.        ]]


In [36]:
import numpy as np
# vd 3:
A = input_matrix()
k = 2
print(A ** k)

Nhập kích thước ma trận vuông n x n:  2


Nhập từng dòng của ma trận, cách nhau bởi dấu cách:


Dòng 1:  1 0
Dòng 2:  0 9


[[ 1.  0.]
 [ 0. 81.]]


In [46]:
import numpy as np
#vd 4:
from sympy import symbols , Matrix, det, solve
m = symbols('m')
A = Matrix([
    [m +1 , 1 , 3],
    [2,m+2,0],
    [2*m,1,3]])
det_A = det(A)
hung = solve(det_A , m)
for i in hung:
    print(f'm != {i}')

m != -2
m != 1


In [33]:
# chapter 2
# slide 22:
import numpy as np
# Nhập vector từ người dùng
num_vectors = int(input("Nhập số chiều của vector: "))
vector_dim = int(input("Nhập số lượng vector: "))

vectors = []
print("Nhập từng vector (các phần tử cách nhau bằng dấu cách):")
for i in range(num_vectors):
    vector = list(map(float, input(f"Vector {i+1}: ").split()))
    if len(vector) != vector_dim:
        print("Lỗi: Số phần tử không đúng, vui lòng nhập lại!")
        exit()
    vectors.append(vector)
# chuyển đổi sang numpy array và thực hiện Gram-Schimidt
V = np.array(vectors).T  # Chuyển ma trận để mỗi cột là một vector

# Áp dụng Gram-Schmidt
U = gram_schmidt(V)

print("\nCác vector trực chuẩn hóa:")
print(U.T)  # Chuyển lại dạng vector ban đầu


Nhập số chiều của vector:  3
Nhập số lượng vector:  3


Nhập từng vector (các phần tử cách nhau bằng dấu cách):


Vector 1:  1 -1 1
Vector 2:  -1 1 1
Vector 3:  1 1 -1



Các vector trực chuẩn hóa:
[[ 0.57735027 -0.57735027  0.57735027]
 [-0.40824829  0.40824829  0.81649658]
 [ 0.70710678  0.70710678  0.        ]]


In [ ]:
# slide 20

In [22]:
import numpy as np  

B = [
    [1, 1, 1, 1],
    [0, 1, 1, 1],
    [1, 0, 1, 1],
    [1, 1, 0, 1]
]

S = [
    [1, 1, 0, 0],
    [0, 1, 1, 0],
    [0, 0, 1, 1],
    [1, 0, 0, 0]
]
B_matrix = np.array(B).T
print(B_matrix)
S_matrix = np.array(S).T
print(S_matrix)
det_B = np.linalg.det(B_matrix)
det_S = np.linalg.det(S_matrix)
print(f"B: {det_B}")
print(f"S: {det_S}")


P_S_from_B = np.linalg.inv(S_matrix) @ B_matrix
print("Ta có ma trận chuyển cơ sở:")
print(P_S_from_B)
print("Tọa độ vecto theo cơ sở B:")
print(np.linalg.inv(P_S_from_B) @ u_S)

[[1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]
 [1 1 1 1]]
[[1 0 0 1]
 [1 1 0 0]
 [0 1 1 0]
 [0 0 1 0]]
B: 1.0
S: -1.0
Ta có ma trận chuyển cơ sở:
[[ 1.  1.  0.  2.]
 [ 0.  0.  0. -1.]
 [ 1.  1.  1.  1.]
 [ 0. -1.  1. -1.]]
Tọa độ vecto theo cơ sở B:
[-9.  6.  4.  2.]


In [12]:
# slide 25
import numpy as np  
from hung import is_linear_mapping,find_image,find_kernel,rank_of_vectors
A = np.array([
    [1,0],
    [0,1],
    [1,1]])
print('f là ánh xa 5 tuyến tính:',is_linear_mapping(A))
print('Anh cua f la: imf = span{(1,0),(0,1),(1,1)}')
print('kerf là: kerf = {(0,0)}')
rank = np.linalg.matrix_rank(A)
nullity = A.shape[1] - rank  # Số khuyết = số biến - hạng
print(f"\nhạng của f (rank): {rank}")
print(f" Số khuyết của f (nullity): {nullity}")


f là ánh xa 5 tuyến tính: True
Anh cua f la: imf = span{(1,0),(0,1),(1,1)}
kerf là: kerf = {(0,0)}

hạng của f (rank): 2
 Số khuyết của f (nullity): 0


In [14]:
# slide 26
import numpy as np

# Giả sử ma trận A có kích thước m x n
m = int(input('số hàng của ma trận là:'))
n = int(input('số cột của ma trận là:'))
A = np.zeros((m,n))
for i in range(m):
    for j in range(n):
        A[i][j] = input(f'nhập phần tử hàng {i+1} cột {j+1} của ma trận A:')      
        print(A, '\n')
print('ta có ma trận A:')
print(A)
# Tìm hạng của ma trận A
rank = np.linalg.matrix_rank(A)

# Số chiều của Ker(f)
dim_ker = A.shape[1] - rank  # n - rank(A)

# Tìm nghiệm của hệ Ax = 0 (sử dụng SVD)
U, s, Vh = np.linalg.svd(A)
null_space_basis = Vh[rank:].T

print("Ker(f) có số chiều:", dim_ker)
print("Cơ sở của Ker(f):\n", null_space_basis)

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 2. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 2. 3.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 2. 3.]
 [1. 0. 0.]
 [0. 0. 0.]] 

[[1. 2. 3.]
 [1. 3. 0.]
 [0. 0. 0.]] 

[[1. 2. 3.]
 [1. 3. 7.]
 [0. 0. 0.]] 

[[1. 2. 3.]
 [1. 3. 7.]
 [1. 0. 0.]] 

[[1. 2. 3.]
 [1. 3. 7.]
 [1. 4. 0.]] 

[[1. 2. 3.]
 [1. 3. 7.]
 [1. 4. 5.]] 

ta có ma trận A:
[[1. 2. 3.]
 [1. 3. 7.]
 [1. 4. 5.]]
Ker(f) có số chiều: 0
Cơ sở của Ker(f):
 []


In [6]:
# chapter 3
import sympy as sp
x1, x2, x3 = sp.symbols('x1 x2 x3', real=True)
f_vec = sp.Matrix([x1, x2, x3])
print("f_vec =",f_vec)
J = f_vec.jacobian([x1, x2, x3])
print("Jacobian =")
print(J)

f_vec = Matrix([[x1], [x2], [x3]])
Jacobian =
Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


In [8]:
a1, a2, a3 = sp.symbols('a1 a2 a3', real=True)
a = sp.Matrix([a1, a2, a3])
x = sp.Matrix([x1, x2, x3])
# f(x) = a^T x = a1*x1 + a2*x2 + a3*x3
f = a.dot(x)
grad_f = sp.derive_by_array(f, (x1, x2, x3))
print("Gradient", grad_f)

Gradient of a^T x = [a1, a2, a3]


In [18]:
A11, A12, A13 = sp.symbols('A11 A12 A13', real=True)
A21, A22, A23 = sp.symbols('A21 A22 A23', real=True)
A31, A32, A33 = sp.symbols('A31 A32 A33', real=True)
A = sp.Matrix([
    [A11, A12, A13],
    [A21, A22, A23],
    [A31, A32, A33]
])
f = (x.transpose() * A * x)
print(f)
print()
f = (x.transpose() * A * x)[0]
print(f)
print()
grad_f = sp.derive_by_array(f, (x1, x2, x3))
print("Gradient \n", grad_f)

Matrix([[x1*(A11*x1 + A21*x2 + A31*x3) + x2*(A12*x1 + A22*x2 + A32*x3) + x3*(A13*x1 + A23*x2 + A33*x3)]])

x1*(A11*x1 + A21*x2 + A31*x3) + x2*(A12*x1 + A22*x2 + A32*x3) + x3*(A13*x1 + A23*x2 + A33*x3)

Gradient of x^T A x = 
 [2*A11*x1 + A12*x2 + A13*x3 + A21*x2 + A31*x3, A12*x1 + A21*x1 + 2*A22*x2 + A23*x3 + A32*x3, A13*x1 + A23*x2 + A31*x1 + A32*x2 + 2*A33*x3]


In [20]:
f = x.dot(x)
grad_f = sp.derive_by_array(f, (x1, x2, x3))
print("Gradient", grad_f)

Gradient [2*x1, 2*x2, 2*x3]


In [24]:
b1, b2, b3 = sp.symbols('b1 b2 b3', real=True)
b = sp.Matrix([b1, b2, b3])
f = (A*x - b).dot(A*x - b) 
grad_f = sp.derive_by_array(f, (x1, x2, x3))
print("Gradient \n", grad_f)

Gradient 
 [2*A11*(A11*x1 + A12*x2 + A13*x3 - b1) + 2*A21*(A21*x1 + A22*x2 + A23*x3 - b2) + 2*A31*(A31*x1 + A32*x2 + A33*x3 - b3), 2*A12*(A11*x1 + A12*x2 + A13*x3 - b1) + 2*A22*(A21*x1 + A22*x2 + A23*x3 - b2) + 2*A32*(A31*x1 + A32*x2 + A33*x3 - b3), 2*A13*(A11*x1 + A12*x2 + A13*x3 - b1) + 2*A23*(A21*x1 + A22*x2 + A23*x3 - b2) + 2*A33*(A31*x1 + A32*x2 + A33*x3 - b3)]


In [28]:
x = sp.symbols('x1 x2 x3', real=True)
x_vec = sp.Matrix(x)
a = sp.symbols('a1 a2 a3', real=True)
b = sp.symbols('b1 b2 b3', real=True)
a_vec = sp.Matrix(a)
b_vec = sp.Matrix(b)
f_expr = a_vec.dot(b_vec) * x_vec.dot(x_vec)
grad_f = sp.derive_by_array(f_expr, x)
print("Gradient:", grad_f)

Gradient: [2*x1*(a1*b1 + a2*b2 + a3*b3), 2*x2*(a1*b1 + a2*b2 + a3*b3), 2*x3*(a1*b1 + a2*b2 + a3*b3)]


In [30]:
f_expr_2 = (a_vec.dot(x_vec)) * (x_vec.dot(b_vec))
grad_f_2 = sp.derive_by_array(f_expr_2, x)
print("Gradient:", grad_f_2)

Gradient: [a1*(b1*x1 + b2*x2 + b3*x3) + b1*(a1*x1 + a2*x2 + a3*x3), a2*(b1*x1 + b2*x2 + b3*x3) + b2*(a1*x1 + a2*x2 + a3*x3), a3*(b1*x1 + b2*x2 + b3*x3) + b3*(a1*x1 + a2*x2 + a3*x3)]


In [ ]:
# trang ben canh (next side)

In [38]:
import sympy as sp
X11, X12, X21, X22 = sp.symbols('X11 X12 X21 X22', real=True)
X = sp.Matrix([
    [X11, X12],
    [X21, X22]
])
f_trace = X.trace()
print(f_trace)
var_X = (X11, X12, X21, X22)
grad_list = sp.derive_by_array(f_trace, var_X)
print(grad_list)
grad_mat = sp.Matrix(grad_list).reshape(2, 2)
print(grad_mat)

X11 + X22
[1, 0, 0, 1]
Matrix([[1, 0], [0, 1]])


In [44]:
A11, A12, A21, A22 = sp.symbols('A11 A12 A21 A22', real=True)
A = sp.Matrix([
    [A11, A12],
    [A21, A22]
])
f_tr = (A.T * X).trace()
print(f_tr)
print()
grad_list_2 = sp.derive_by_array(f_tr, var_X)
print(grad_list_2)
print()
grad_mat_2 = sp.Matrix(grad_list_2).reshape(2, 2)
print(grad_mat_2)

A11*X11 + A12*X12 + A21*X21 + A22*X22

[A11, A12, A21, A22]

Matrix([[A11, A12], [A21, A22]])


In [50]:
f_trXAX = (X.T * A * X).trace()
grad_list_3 = sp.derive_by_array(f_trXAX, var_X)
grad_mat_3 = sp.Matrix(grad_list_3).reshape(2, 2)
print(grad_mat_3)

Matrix([[2*A11*X11 + A12*X21 + A21*X21, 2*A11*X12 + A12*X22 + A21*X22], [A12*X11 + A21*X11 + 2*A22*X21, A12*X12 + A21*X12 + 2*A22*X22]])


In [54]:
f_normX = (X.T*X).trace()
grad_list_4 = sp.derive_by_array(f_normX, var_X)
grad_mat_4 = sp.Matrix(grad_list_4).reshape(2, 2)
print(grad_mat_4)

Matrix([[2*X11, 2*X12], [2*X21, 2*X22]])


In [58]:
B11, B12, B21, B22 = sp.symbols('B11 B12 B21 B22', real=True)
B = sp.Matrix([
    [B11, B12],
    [B21, B22]
])
f_AXB = (A*X - B)
f_AXB_norm = (f_AXB.T * f_AXB).trace()
grad_list_5 = sp.derive_by_array(f_AXB_norm, var_X)
grad_mat_5 = sp.Matrix(grad_list_5).reshape(2, 2)
print(grad_mat_5)

Matrix([[2*A11*(A11*X11 + A12*X21 - B11) + 2*A21*(A21*X11 + A22*X21 - B21), 2*A11*(A11*X12 + A12*X22 - B12) + 2*A21*(A21*X12 + A22*X22 - B22)], [2*A12*(A11*X11 + A12*X21 - B11) + 2*A22*(A21*X11 + A22*X21 - B21), 2*A12*(A11*X12 + A12*X22 - B12) + 2*A22*(A21*X12 + A22*X22 - B22)]])


In [60]:
X11, X12, X13 = sp.symbols('X11 X12 X13', real=True)
X21, X22, X23 = sp.symbols('X21 X22 X23', real=True)
X = sp.Matrix([
    [X11, X12, X13],
    [X21, X22, X23]
])
a1, a2 = sp.symbols('a1 a2', real=True)
b1, b2, b3 = sp.symbols('b1 b2 b3', real=True)
a_mat = sp.Matrix([a1, a2])
b_mat = sp.Matrix([b1, b2, b3])
f_expr_3 = a_mat.transpose() * X * b_mat 
vars_X = (X11, X12, X13, X21, X22, X23)
grad_list_3 = sp.derive_by_array(f_expr_3[0], vars_X)
grad_mat_3 = sp.Matrix(grad_list_3).reshape(2, 3)
grad_mat_3_simpl = sp.simplify(grad_mat_3)
print("\n3) f(X) = a^T X b")
print("Gradient wrt X =")
sp.pprint(grad_mat_3_simpl)



3) f(X) = a^T X b
Gradient wrt X =
⎡a₁⋅b₁  a₁⋅b₂  a₁⋅b₃⎤
⎢                   ⎥
⎣a₂⋅b₁  a₂⋅b₂  a₂⋅b₃⎦


In [62]:

A11, A12, A21, A22 = sp.symbols('A11 A12 A21 A22', real=True)
B11, B12, B21, B22 = sp.symbols('B11 B12 B21 B22', real=True)

A_mat = sp.Matrix([[A11, A12],
                   [A21, A22]])
B_mat = sp.Matrix([[B11, B12],
                   [B21, B22]])

X11, X12, X21, X22 = sp.symbols('X11 X12 X21 X22', real=True)
X_mat = sp.Matrix([[X11, X12],
                   [X21, X22]])

f_expr_4 = (A_mat.T * X_mat * B_mat).trace()

vars_X_2x2 = (X11, X12, X21, X22)
grad_list_4 = sp.derive_by_array(f_expr_4, vars_X_2x2)

# reshape về 2x2
grad_mat_4 = sp.Matrix(grad_list_4).reshape(2, 2)
grad_mat_4_simpl = sp.simplify(grad_mat_4)

print("\n4) f(X) = trace(A^T X B)")
print("Gradient wrt X =")
sp.pprint(grad_mat_4_simpl)



4) f(X) = trace(A^T X B)
Gradient wrt X =
⎡A₁₁⋅B₁₁ + A₁₂⋅B₁₂  A₁₁⋅B₂₁ + A₁₂⋅B₂₂⎤
⎢                                    ⎥
⎣A₂₁⋅B₁₁ + A₂₂⋅B₁₂  A₂₁⋅B₂₁ + A₂₂⋅B₂₂⎦
