In [ ]:
import numpy as np

In [38]:
# slide 4
m = int(input('số hàng của ma trận là:'))
n = int(input('số cột của ma trận là:'))

số hàng của ma trận là: 2
số cột của ma trận là: 2


In [40]:
A = np.zeros((m,n))
for i in range(m):
    for j in range(n):
        A[i][j] = input(f'nhập phần tử hàng {i+1} cột {j+1} của ma trận A:')      
        print(A, '\n')
print('ta có ma trận A:')
print(A)

nhập phần tử hàng 1 cột 1 của ma trận A: 1


[[1. 0.]
 [0. 0.]] 



nhập phần tử hàng 1 cột 2 của ma trận A: 2


[[1. 2.]
 [0. 0.]] 



nhập phần tử hàng 2 cột 1 của ma trận A: 3


[[1. 2.]
 [3. 0.]] 



nhập phần tử hàng 2 cột 2 của ma trận A: 4


[[1. 2.]
 [3. 4.]] 

ta có ma trận A:
[[1. 2.]
 [3. 4.]]


In [46]:
# slide 5
A_T = A.T
print('ta có ma trận chuyển vị là:')
print(A_T)

ta có ma trận chuyển vị là:
[[1. 3.]
 [2. 4.]]


In [48]:
# slide 6
import numpy as np

In [50]:
n = int(input('Hãy nhập kích thước của ma trận vuông: '))

Hãy nhập kích thước của ma trận vuông:  2


In [62]:
A = []
for i in range(n):
    row = list(map(float,input(f'Hàng {i+1}:').split()))
    A.append(row)
print(np.array(A))

Hàng 1: 1 2 
Hàng 2: 3 4


[[1. 2.]
 [3. 4.]]


In [64]:
import numpy as np

In [66]:
n = int(input('số cột của ma trận là:'))
m = int(input('số hàng của ma trận là:'))

số cột của ma trận là: 2
số hàng của ma trận là: 3


In [72]:
A = []
for i in range(n):
    row = list(map(complex, input(f"Hàng {i+1}: ").split()))
    A.append(row)
A = np.array(A, dtype=np.complex128)
print('Ma trận chuyển vị liên hợp:')
print(A.conj().T)

Hàng 1:  2 3 4
Hàng 2:  1 2 3


Ma trận chuyển vị liên hợp:
[[2.-0.j 1.-0.j]
 [3.-0.j 2.-0.j]
 [4.-0.j 3.-0.j]]


In [1]:
# slide 7
import numpy as np

In [3]:
# Nhập kích thước của ma trận vuông {nxn}:
n = int(input("Nhập kích thước của ma trận vuông {n}:"))

A = []
for i in range(n):
    row = list(map(float,input(f"hàng {i+1}:").split()))
    A.append(row)
A = np.array(A)
print("\n Ma trận vuông A:")
print(A)

Nhập kích thước của ma trận vuông {n}: 3
hàng 1: 1 2 3
hàng 2: 2 3 4
hàng 3: 3 4 5



 Ma trận vuông A:
[[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]]


In [9]:
# slide 8
import numpy as np
def row_echelon_form(A):
    A = A.astype(float)
    rows,cols = A.shape
    pivot_row = 0
    for col in range(cols):
        max_row = pivot_row + np.argmax(np.abs(A[pivot_row:,col]))
        if A[max_row,col] == 0:
            continue
        A[[pivot_row,max_row]] = A[[max_row,pivot_row]]
        A[pivot_row] = A[pivot_row] / A[pivot_row,col]
        for row in range(pivot_row + 1,rows):
            A[row] -= A[row,col] *A[pivot_row]
        pivot_row += 1
        if pivot_row == rows:
            break
    return A
m = int(input("Nhập vào hàng:"))
n = int(input("nhập vào cột:"))
A = []
for i in range(m):
    row = list(map(float,input(f"nhập vào hàng {i+1}:").split()))
    A.append(row)
A =np.array(A)
A_ref = row_echelon_form(A.copy())
print(A_ref)

Nhập vào hàng: 2 
nhập vào cột: 2
nhập vào hàng 1: 1 2
nhập vào hàng 2: 2 3


[[1.  1.5]
 [0.  1. ]]


In [11]:
# slide 9
import numpy as np

In [17]:
n = int(input("nhập kích thước ma trận vuông(n): "))
A = np.random.randint(1,10,(n,n))
upper = np.triu(A)
lower = np.tril(A)
print("ma trận ban đầu:")
print(A)
print("\n ma trận tam giác trên là:")
print(upper)
print("\n ma trận tam giác dưới là:")
print(lower)

nhập kích thước ma trận vuông(n):  2


ma trận ban đầu:
[[2 5]
 [1 5]]

 ma trận tam giác trên là:
[[2 5]
 [0 5]]

 ma trận tam giác dưới là:
[[2 0]
 [1 5]]


In [29]:
# slide 10
import numpy as np
def tao_matran_duong(n):
    B = np.random.randint(-10,-1,(n,n))
    A = np.dot(B.T,B)
    return A,B
n = int(input("nhập vào kích thước của ma trận vuông {n}:"))
A,B = tao_matran_duong(n)
print("ta có ma trận ban đầu là:")
print(B)
print("ta có ma trận xác định dương là:")
print(A)

nhập vào kích thước của ma trận vuông {n}: 2


ta có ma trận ban đầu là:
[[-3 -8]
 [-6 -6]]
ta có ma trận xác định dương là:
[[ 45  60]
 [ 60 100]]


In [67]:
# slide 11
import numpy as np
m = int(input("nhập số hàng của ma trận A:"))
n = int(input("nhập vào cột của ma trận A cũng là số hàng của ma trận B:"))
p = int(input("nhập vào số cột của ma trận B:"))

print("\n Nhập vào ma trận A:")
A = np.array([[int(input(f"phần tử A[{j+1}][{i +1}]")) for i  in range(n) ] for j in range(m)])
print(A.shape)
print("\n nhập vào ma trận B:")
B = np.array([[int(input(f"phần tử B[{j+1}][{i +1}]"))for i in range(p)] for j in range(n)])
print(B.shape)

C = A@B # hoặc sử dụng dot(A,B)
D = A + B.T
print("\n nhân 2 ma trận là:")
print(C)
print("\n công 2 ma trận là:")
print(D)

nhập số hàng của ma trận A: 2
nhập vào cột của ma trận A cũng là số hàng của ma trận B: 3
nhập vào số cột của ma trận B: 2



 Nhập vào ma trận A:


phần tử A[1][1] 1
phần tử A[1][2] 1
phần tử A[1][3] 1
phần tử A[2][1] 1
phần tử A[2][2] 1
phần tử A[2][3] 1


(2, 3)

 nhập vào ma trận B:


phần tử B[1][1] 1
phần tử B[1][2] 1
phần tử B[2][1] 1
phần tử B[2][2] 1
phần tử B[3][1] 1
phần tử B[3][2] 1


(3, 2)

 nhân 2 ma trận là:
[[3 3]
 [3 3]]

 công 2 ma trận là:
[[2 2 2]
 [2 2 2]]


In [23]:
# slide 13
import numpy as np
n = int(input("nhập kích thước của ma trận vuông {n}:"))

print("\n nhập ma trận A:")
A = np.array([[float(input(f"A[{i}][{j}]: ")) for j in range(n)] for i in range(n)])
det_A = np.linalg.det(A)
if det_A == 0:
    print("ma trận A không phải là ma trận khả nghịch:")
else:
    A_inv = np.linalg.inv(A)
    print("\n ma trận khả nghịch của A là:")
    print(A_inv)

    print("\n kiểm tra tính khả nghịch của ma trận A:")
    print(np.round(np.dot(A,A_inv),5))

nhập kích thước của ma trận vuông {n}: 4



 nhập ma trận A:


A[0][0]:  -1
A[0][1]:  0
A[0][2]:  1
A[0][3]:  -1
A[1][0]:  2
A[1][1]:  1
A[1][2]:  -3
A[1][3]:  4
A[2][0]:  1
A[2][1]:  2
A[2][2]:  -2
A[2][3]:  8
A[3][0]:  -2
A[3][1]:  0
A[3][2]:  2
A[3][3]:  1



 ma trận khả nghịch của A là:
[[-1.33333333 -2.          1.         -1.33333333]
 [ 2.33333333 -1.          1.         -1.66666667]
 [-1.         -2.          1.         -1.        ]
 [-0.66666667 -0.         -0.          0.33333333]]

 kiểm tra tính khả nghịch của ma trận A:
[[ 1. -0.  0. -0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0. -0.  0.  1.]]


In [1]:
# slide 14 
import numpy as np

In [11]:
def random_orthogonal_matrix(n):
    """
    sinh ra một ma trận trực giao ngẫu nhiên kích thước {nxn}.

    :param n: kích thước của ma trận
    :return: Ma trận trực giao (Numpy array)
    """

    random_matrix = np.random.rand(n,n)
    Q, h = np.linalg.qr(random_matrix)
    return Q,h
hung,hung1 = random_orthogonal_matrix(3)
print("ta co ma tran truc giao la:\n",hung)
print(hung1)

ta co ma tran truc giao la:
 [[-0.25879487 -0.61980595 -0.74085478]
 [-0.70035823 -0.40780831  0.58582483]
 [-0.66522445  0.6704722  -0.3285475 ]]
[[-1.0662318  -0.74555187 -1.06994412]
 [ 0.         -0.22023199 -0.49541998]
 [ 0.          0.         -0.17299958]]


In [13]:
# slide 17
import numpy as np

def determinant_laplace(matrix):
    """
    Tính định thức của ma trận bằng phương pháp khai triển Laplace (đệ quy).
    :param matrix: Ma trận vuông (numpy array hoặc list lồng nhau)
    :return: Giá trị định thức của ma trận
    """
    matrix = np.array(matrix)
    n = matrix.shape[0]

    # Điều kiện dừng: Ma trận 1x1
    if n == 1:
        return matrix[0][0]
    # Điều kiện dừng: Ma trận 2x2
    elif n == 2:
        return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
    else:
        det = 0
        for i in range(n):
            for j in range(n):
                # Xóa hàng đầu tiên và cột j để tạo ma trận con
                sub_matrix = np.delete(np.delete(matrix[1:], j, axis=1), i, axis=0)
                cofactor = (-1) ** (i + j) * matrix[0][j] * determinant_laplace(sub_matrix)
                det += cofactor
        return det

def input_matrix():
    n = int(input("Nhập kích thước ma trận vuông n x n: "))
    matrix = []
    print("Nhập từng dòng của ma trận, cách nhau bởi dấu cách:")
    for i in range(n):
        row = list(map(float, input(f"Dòng {i+1}: ").split()))
        matrix.append(row)
    return np.array(matrix)

# Chạy chương trình
if __name__ == "__main__":
    matrix = input_matrix()
    det = determinant_laplace(matrix)
    print(f"Định thức của ma trận là: {det}")


In [17]:
# slide 21 
import numpy as np

In [19]:
def input_matrix():
    n,m = map(int,input("nhập số hàng và số cột của ma trận( cách nhau bởi dấu cách):").split())
    print("nhập từng dòng của ma trận, cách nhau bởi dấu cách:")
    matrix = []
    for i in range(n):
        row = list(map(float,input(f"Dòng {i+1}:").split()))
        matrix.append(row)
    return np.array(matrix)
A =input_matrix()
rank = np.linalg.matrix_rank(A)
print("Hạng của ma trận:",rank)

nhập số hàng và số cột của ma trận( cách nhau bởi dấu cách): 2 2


nhập từng dòng của ma trận, cách nhau bởi dấu cách:


Dòng 1:  1 2
Dòng 2: 3 4


Hạng của ma trận: 2


In [ ]:
# slide 24
import numpy as np

def gauss_jordan_inverse(matrix):
    """
    Tìm ma trận nghịch đảo bằng phương pháp Gauss-Jordan.
    
    :param matrix: Ma trận vuông (numpy array)
    :return: Ma trận nghịch đảo nếu tồn tại, ngược lại báo lỗi
    """
    matrix = np.array(matrix, dtype=float)
    n = matrix.shape[0]

    # Tạo ma trận mở rộng [A | I]
    augmented_matrix = np.hstack([matrix, np.eye(n)])

    # Áp dụng phép biến đổi hàng
    for i in range(n):
        # Tìm phần tử chính (pivot)
        pivot = augmented_matrix[i, i]
        if abs(pivot) < 1e-10:  # Kiểm tra nếu phần tử pivot quá nhỏ hoặc bằng 0
            raise ValueError("Ma trận không khả nghịch!")

        # Chia hàng i cho pivot để pivot trở thành 1
        augmented_matrix[i] = augmented_matrix[i] / pivot

        # Dùng hàng i để khử các phần tử khác trong cột
        for j in range(n):
            if i != j:
                factor = augmented_matrix[j, i]
                augmented_matrix[j] -= factor * augmented_matrix[i]

    # Phần bên phải là ma trận nghịch đảo
    inverse_matrix = augmented_matrix[:, n:]
    return inverse_matrix

# Nhập ma trận từ người dùng
def input_matrix():
    n = int(input("Nhập kích thước ma trận vuông n x n: "))
    matrix = []
    print("Nhập từng dòng của ma trận, cách nhau bởi dấu cách:")
    for i in range(n):
        row = list(map(float, input(f"Dòng {i+1}: ").split()))
        matrix.append(row)
    return np.array(matrix)

# Chạy chương trình
try:
    A = input_matrix()
    A_inv = gauss_jordan_inverse(A)
    print("Ma trận nghịch đảo của A là:\n", A_inv)
except ValueError as e:
    print(e)
