In [1]:
# chapter 1
import numpy as np
from hung import input_matrix,gauss_jordan_inverse,gram_schmidt
# vd1:

In [12]:
try:
    A = input_matrix()
    A_inv = gauss_jordan_inverse(A)
    print("Ma trận nghịch đảo của A là:\n", A_inv)
except ValueError as e:
    print(e)

Nhập kích thước ma trận vuông n x n:  4


Nhập từng dòng của ma trận, cách nhau bởi dấu cách:


Dòng 1:  -1 0 1 -1
Dòng 2:  2 1 -3 4
Dòng 3:  1 2 -2 8
Dòng 4:  -2 0 2 1


Ma trận nghịch đảo của A là:
 [[-1.33333333 -2.          1.         -1.33333333]
 [ 2.33333333 -1.          1.         -1.66666667]
 [-1.         -2.          1.         -1.        ]
 [-0.66666667  0.          0.          0.33333333]]


In [16]:
try:
    B = input_matrix()
    B_inv = gauss_jordan_inverse(B)
    print("Ma trận nghịch đảo của A là:\n", B_inv)
except ValueError as e:
    print(e)

Nhập kích thước ma trận vuông n x n:  4


Nhập từng dòng của ma trận, cách nhau bởi dấu cách:


Dòng 1:  1 1 1 1
Dòng 2:  2 2 3 5
Dòng 3:  3 3 4 5
Dòng 4:  1 1 1 2


Ma trận không khả nghịch!


In [18]:
# vd2:
A_T = A.T
A_T_inv = gauss_jordan_inverse(A_T)

In [20]:
print("X:\n",np.dot(B,A_T_inv) + A)

X:
 [[ -4.66666667   0.66666667  -2.          -1.33333333]
 [ -8.33333333  -1.66666667 -11.           4.33333333]
 [-11.66666667   1.66666667 -12.           7.66666667]
 [ -7.          -1.          -2.           1.        ]]


In [24]:
import numpy as np
# vd 3:
A = input_matrix()
k = 3
print(A ** k)

Nhập kích thước ma trận vuông n x n:  2


Nhập từng dòng của ma trận, cách nhau bởi dấu cách:


Dòng 1:  1 0
Dòng 2:  0 9


[[  1.   0.]
 [  0. 729.]]


In [29]:
import numpy as np
#vd 4:
from sympy import symbols , Matrix, det, solve
m = symbols('m')
A = Matrix([
    [m +1 , 1 , 3],
    [2,m+2,0],
    [2*m,1,3]])
det_A = det(A)
hung = solve(det_A , m)
for i in hung:
    print(f'm != {i}')

m != -2
m != 1
