In [3]:
import numpy as np
from hung import input_matrix,gauss_jordan_inverse,gram_schmidt

In [5]:
# chapter 2
# slide 22:
import numpy as np
# Nhập vector từ người dùng
num_vectors = int(input("Nhập số chiều của vector: "))
vector_dim = int(input("Nhập số lượng vector: "))

vectors = []
print("Nhập từng vector (các phần tử cách nhau bằng dấu cách):")
for i in range(num_vectors):
    vector = list(map(float, input(f"Vector {i+1}: ").split()))
    if len(vector) != vector_dim:
        print("Lỗi: Số phần tử không đúng, vui lòng nhập lại!")
        exit()
    vectors.append(vector)
# chuyển đổi sang numpy array và thực hiện Gram-Schimidt
V = np.array(vectors).T  # Chuyển ma trận để mỗi cột là một vector

# Áp dụng Gram-Schmidt
U = gram_schmidt(V)

print("\nCác vector trực chuẩn hóa:")
print(U.T)  # Chuyển lại dạng vector ban đầu


Nhập số chiều của vector:  3
Nhập số lượng vector:  3


Nhập từng vector (các phần tử cách nhau bằng dấu cách):


Vector 1:  1 -1 1
Vector 2:  -1 1 1
Vector 3:  1 1 -1



Các vector trực chuẩn hóa:
[[ 0.57735027 -0.57735027  0.57735027]
 [-0.40824829  0.40824829  0.81649658]
 [ 0.70710678  0.70710678  0.        ]]


In [19]:
# slide 20
import numpy as np  

B = [
    [1, 1, 1, 1],
    [0, 1, 1, 1],
    [1, 0, 1, 1],
    [1, 1, 0, 1]
]

S = [
    [1, 1, 0, 0],
    [0, 1, 1, 0],
    [0, 0, 1, 1],
    [1, 0, 0, 0]
]
B_matrix = np.array(B).T
print(B_matrix)
S_matrix = np.array(S).T
print(S_matrix)
det_B = np.linalg.det(B_matrix)
det_S = np.linalg.det(S_matrix)
print(f"B: {det_B}")
print(f"S: {det_S}")
u_S = np.array([1,-2,3,-4])

P_S_from_B = np.linalg.inv(S_matrix) @ B_matrix
print("Ta có ma trận chuyển cơ sở:")
print(P_S_from_B)
print("Tọa độ vecto theo cơ sở B:")
print(np.linalg.inv(P_S_from_B) @ u_S)

[[1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]
 [1 1 1 1]]
[[1 0 0 1]
 [1 1 0 0]
 [0 1 1 0]
 [0 0 1 0]]
B: 1.0
S: -1.0
Ta có ma trận chuyển cơ sở:
[[ 1.  1.  0.  2.]
 [ 0.  0.  0. -1.]
 [ 1.  1.  1.  1.]
 [ 0. -1.  1. -1.]]
Tọa độ vecto theo cơ sở B:
[-9.  6.  4.  2.]


In [21]:
# slide 25
import numpy as np  
from hung import is_linear_mapping,find_image,find_kernel,rank_of_vectors
A = np.array([
    [1,0],
    [0,1],
    [1,1]])
print('f là ánh xa 5 tuyến tính:',is_linear_mapping(A))
print('Anh cua f la: imf = span{(1,0),(0,1),(1,1)}')
print('kerf là: kerf = {(0,0)}')
rank = np.linalg.matrix_rank(A)
nullity = A.shape[1] - rank  # Số khuyết = số biến - hạng
print(f"\nhạng của f (rank): {rank}")
print(f" Số khuyết của f (nullity): {nullity}")


f là ánh xa 5 tuyến tính: True
Anh cua f la: imf = span{(1,0),(0,1),(1,1)}
kerf là: kerf = {(0,0)}

hạng của f (rank): 2
 Số khuyết của f (nullity): 0


In [25]:
# slide 26
import numpy as np

# Giả sử ma trận A có kích thước m x n
m = int(input('số hàng của ma trận là:'))
n = int(input('số cột của ma trận là:'))
A = np.zeros((m,n))
for i in range(m):
    for j in range(n):
        A[i][j] = input(f'nhập phần tử hàng {i+1} cột {j+1} của ma trận A:')      
        print(A, '\n')
print('ta có ma trận A:')
print(A)
# Tìm hạng của ma trận A
rank = np.linalg.matrix_rank(A)

# Số chiều của Ker(f)
dim_ker = A.shape[1] - rank  # n - rank(A)

# Tìm nghiệm của hệ Ax = 0 (sử dụng SVD)
U, s, Vh = np.linalg.svd(A)
null_space_basis = Vh[rank:].T

print("Ker(f) có số chiều:", dim_ker)
print("Cơ sở của Ker(f):\n", null_space_basis)

số hàng của ma trận là: 3
số cột của ma trận là: 3
nhập phần tử hàng 1 cột 1 của ma trận A: 1


[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 



nhập phần tử hàng 1 cột 2 của ma trận A: 2


[[1. 2. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 



nhập phần tử hàng 1 cột 3 của ma trận A: 3


[[1. 2. 3.]
 [0. 0. 0.]
 [0. 0. 0.]] 



nhập phần tử hàng 2 cột 1 của ma trận A: 1


[[1. 2. 3.]
 [1. 0. 0.]
 [0. 0. 0.]] 



nhập phần tử hàng 2 cột 2 của ma trận A: 3


[[1. 2. 3.]
 [1. 3. 0.]
 [0. 0. 0.]] 



nhập phần tử hàng 2 cột 3 của ma trận A: 7


[[1. 2. 3.]
 [1. 3. 7.]
 [0. 0. 0.]] 



nhập phần tử hàng 3 cột 1 của ma trận A: 1


[[1. 2. 3.]
 [1. 3. 7.]
 [1. 0. 0.]] 



nhập phần tử hàng 3 cột 2 của ma trận A: 4


[[1. 2. 3.]
 [1. 3. 7.]
 [1. 4. 0.]] 



nhập phần tử hàng 3 cột 3 của ma trận A: 5


[[1. 2. 3.]
 [1. 3. 7.]
 [1. 4. 5.]] 

ta có ma trận A:
[[1. 2. 3.]
 [1. 3. 7.]
 [1. 4. 5.]]
Ker(f) có số chiều: 0
Cơ sở của Ker(f):
 []


In [27]:
# slide 37:
import numpy as np
A = np.array([[-2, 5],
              [-1, 2]])
tri_rieng, vt_rieng = np.linalg.eig(A)
print("Trị riêng:", tri_rieng)
print("\nVéc tơ riêng tương ứng (cột):\n",vt_rieng)

Trị riêng: [0.+1.j 0.-1.j]

Véc tơ riêng tương ứng (cột):
 [[0.91287093+0.j         0.91287093-0.j        ]
 [0.36514837+0.18257419j 0.36514837-0.18257419j]]


In [29]:
# slide 38:
import numpy as np
B = np.array([
    [3, -2, 0],
    [-2, 3, 0],
    [0, 0, 5]
])
tri_rieng, vt_rieng = np.linalg.eig(B)
print("Các trị riêng:", tri_rieng)
print("Các vectơ riêng tương ứng (cột):\n", vt_rieng)

Các trị riêng: [5. 1. 5.]
Các vectơ riêng tương ứng (cột):
 [[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
